name: Deploy Next.js App

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install -g pm2 # Install pm2 globally

      - name: Build the app
        run: npm run build

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }} # Your EC2 user
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} # Your EC2 private SSH key
          EC2_HOST: ${{ secrets.EC2_HOST }} # Your EC2 host (IP address or hostname)
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem  # Save the SSH key to a file
          chmod 600 private_key.pem  # Ensure the key file has the correct permissions

          # Use SSH to deploy to EC2
          ssh -i private_key.pem $EC2_USER@$EC2_HOST <<EOF
            cd /path/to/your/app
            git pull origin master  # Pull the latest code if necessary
            npm install  # Install dependencies
            npm run build  # Build your Next.js app
            pm2 restart ecosystem.config.js  # Restart the app with PM2 (or another command you use)
          EOF

          # Clean up by removing the private key after the deployment
          rm private_key.pem
